# Generated by Django 5.0.3 on 2024-03-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_task_state_remove_task_user_labels_tasks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='labels',
            field=models.ManyToManyField(blank=True, null=True, to='todo.labels'),
        ),
    ]
